FROM debian:bookworm-slim

RUN apt-get update && apt-get install -y ca-certificates && rm -rf /var/lib/apt/lists/*

COPY ./server /usr/local/bin/server
RUN chmod +x /usr/local/bin/server

ENV PORT=8081
EXPOSE 8081

CMD ["/usr/local/bin/server"]
